<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>GetIPlayer.Cli</RootNamespace>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="GetIPlayer.Cli.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../GetIPlayer.Application/GetIPlayer.Application.csproj" />
    <ProjectReference Include="../GetIPlayer.Infrastructure/GetIPlayer.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.CommandLine" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.Logging" />
    <PackageReference Include="Serilog.Extensions.Logging" />
    <PackageReference Include="Serilog.Sinks.Console" />
  </ItemGroup>

</Project>
